import pytest
import asyncio
from httpx import AsyncClient, ASGITransport

# Adjust the import path according to your project structure
# This assumes your main app instance is named 'app' in 'backend.billion_engine'
from backend.billion_engine import app, wallets, profit_events, wallet_scaling_factors

@pytest.fixture(scope="function", autouse=True)
async def reset_state():
    """Resets the in-memory state before each test."""
    wallets.clear()
    profit_events.clear()
    wallet_scaling_factors.clear()
    # If there are any running asyncio tasks from previous tests that need to be cancelled,
    # that would be more complex and might require managing tasks explicitly.
    # For now, clearing state is the primary concern for these tests.

@pytest.mark.asyncio
async def test_collect_wallet_new():
    """Test collecting a new wallet."""
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        response = await ac.post("/collect_wallet", json={"wallet": "test_wallet_1"})
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "registered"
    assert data["wallet"] == "test_wallet_1"
    assert "test_wallet_1" in wallets
    assert "test_wallet_1" in wallet_scaling_factors
    assert wallet_scaling_factors["test_wallet_1"] == 1.0

    # Allow some time for the billion_cycle to start and generate an event
    await asyncio.sleep(0.1) # Reduced sleep for faster tests; may need adjustment

@pytest.mark.asyncio
async def test_collect_wallet_existing():
    """Test collecting an existing wallet."""
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        # First call
        await ac.post("/collect_wallet", json={"wallet": "test_wallet_2"})
        # Second call
        response = await ac.post("/collect_wallet", json={"wallet": "test_wallet_2"})

    assert response.status_code == 200 # Should still be successful
    data = response.json()
    assert data["status"] == "registered" # Or a different status like "already_exists" if we change behavior
    assert data["wallet"] == "test_wallet_2"
    # Ensure it wasn't added twice or reset
    assert wallets.count("test_wallet_2") == 1
    assert wallet_scaling_factors.get("test_wallet_2") == 1.0


@pytest.mark.asyncio
async def test_get_profit_events_empty():
    """Test getting profit events for a wallet with no events."""
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        response = await ac.get("/profit_events?wallet=non_existent_wallet")
    assert response.status_code == 200
    data = response.json()
    assert data["profitEvents"] == []

@pytest.mark.asyncio
async def test_get_profit_events_with_data():
    """Test getting profit events after a wallet is collected and simulated."""
    wallet_name = "event_wallet_1"
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        await ac.post("/collect_wallet", json={"wallet": wallet_name})
        # Wait for billion_cycle to potentially generate some events.
        # This makes the test dependent on timing, which is not ideal but necessary
        # for testing the side effects of the async task in this setup.
        # A very short sleep to allow at least one cycle iteration if possible.
        # The actual profit generation part of billion_cycle has multiple sleeps.
        # We'll check for the wallet's registration and then if any events appear after a longer delay.

        # Give a bit more time for the first profit event to be generated by billion_cycle
        # Original sleeps in billion_cycle: randint(2,5) then 2. So minimum 4 seconds.
        # This is too long for a unit test. We are testing the endpoint, and assuming billion_cycle works.
        # For a true integration test of this, we'd wait longer.
        # Here, we'll manually add a dummy event to test the endpoint's retrieval logic.
        profit_events[wallet_name] = [{"id": "test_evt_1", "amount": 100, "sent": True}]

        response = await ac.get(f"/profit_events?wallet={wallet_name}")

    assert response.status_code == 200
    data = response.json()
    assert len(data["profitEvents"]) == 1
    assert data["profitEvents"][0]["id"] == "test_evt_1"

@pytest.mark.asyncio
async def test_status_empty():
    """Test the status endpoint when no wallets are registered."""
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        response = await ac.get("/status")
    assert response.status_code == 200
    data = response.json()
    assert data["wallets"] == []
    assert data["wallet_scaling_factors"] == {}
    assert data["profit_events"] == {}

@pytest.mark.asyncio
async def test_status_with_data():
    """Test the status endpoint after wallets are registered."""
    wallet_name = "status_wallet_1"
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        await ac.post("/collect_wallet", json={"wallet": wallet_name})
        # Manually add some data to simulate state for testing the status endpoint directly
        profit_events[wallet_name] = [{"id": "status_evt_1", "amount": 200, "sent": False}]
        # wallet_scaling_factors is set by collect_wallet

        response = await ac.get("/status")

    assert response.status_code == 200
    data = response.json()
    assert wallet_name in data["wallets"]
    assert data["wallet_scaling_factors"][wallet_name] == 1.0
    assert len(data["profit_events"][wallet_name]) == 1
    assert data["profit_events"][wallet_name][0]["id"] == "status_evt_1"

# Note: Testing the full asynchronous behavior of billion_cycle, especially cloning
# and scaling factor changes over time, is complex in unit tests.
# These tests focus on the API contract and immediate state changes.
# More comprehensive testing for billion_cycle would require mocking asyncio.sleep
# or using a dedicated test framework for asynchronous tasks.
# The `asyncio.sleep(0.1)` in `test_collect_wallet_new` is a small concession
# to check if the task starts, but not for its full execution.
# In `test_get_profit_events_with_data` and `test_status_with_data`, we are directly
# manipulating the state variables for more predictable testing of those read-endpoints.
# This is because `billion_cycle` has internal sleeps that are too long for fast unit tests.
# A better approach for `billion_cycle` testing would be to refactor it to make it more testable,
# e.g., by injecting a "time" or "scheduler" object.

@pytest.mark.asyncio
async def test_collect_wallet_assigns_random_strategy():
    """Test that collecting a new wallet assigns a random valid strategy and it's reported."""
    wallet_name = "random_strategy_wallet_1"

    # We need to know the available strategy names to check against
    from backend.billion_engine import PREDEFINED_STRATEGIES, wallet_strategies
    possible_strategy_names = [s.value for s in PREDEFINED_STRATEGIES.keys()]

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        # Register the wallet
        response_collect = await ac.post("/collect_wallet", json={"wallet": wallet_name})
        assert response_collect.status_code == 200
        collect_data = response_collect.json()
        assert collect_data["status"] == "registered"
        assert collect_data["wallet"] == wallet_name

        assigned_strategy_in_response = collect_data["strategy"]
        assert assigned_strategy_in_response in possible_strategy_names

        # Check global state
        assert wallet_strategies[wallet_name].value == assigned_strategy_in_response

        # Check /status endpoint
        response_status = await ac.get("/status")
        assert response_status.status_code == 200
        status_data = response_status.json()
        assert status_data["wallets"] == [wallet_name] # Assuming this is the only wallet
        assert status_data["wallet_strategies"][wallet_name] == assigned_strategy_in_response

    # Allow some time for the billion_cycle to start
    await asyncio.sleep(0.1) # Small delay for async task to kick off

@pytest.mark.asyncio
async def test_clone_inherits_strategy_in_state():
    """
    Test that if a clone is created (simulated by manual state update),
    it inherits the parent's strategy in the global state and status endpoint.
    This test focuses on the state aspect, not triggering actual async cloning.
    """
    parent_wallet_name = "parent_wallet_1"
    clone_wallet_name = f"{parent_wallet_name}_clone_1"

    from backend.billion_engine import wallets, wallet_scaling_factors, wallet_strategies, StrategyName, PREDEFINED_STRATEGIES

    # Get a known strategy name to assign to parent
    # For consistency, let's pick one, e.g., LOW_RISK, though in reality it would be random via /collect_wallet
    parent_strategy_name = StrategyName.LOW_RISK
    # Manually simulate parent registration and strategy assignment for test setup simplicity
    wallets.append(parent_wallet_name)
    wallet_scaling_factors[parent_wallet_name] = 1.0
    wallet_strategies[parent_wallet_name] = parent_strategy_name

    # Manually simulate the state changes that occur during cloning
    wallets.append(clone_wallet_name)
    wallet_scaling_factors[clone_wallet_name] = wallet_scaling_factors[parent_wallet_name] * 2 # Example scaling
    wallet_strategies[clone_wallet_name] = wallet_strategies[parent_wallet_name] # Key part: clone inherits strategy

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        response_status = await ac.get("/status")
        assert response_status.status_code == 200
        status_data = response_status.json()

        assert parent_wallet_name in status_data["wallets"]
        assert clone_wallet_name in status_data["wallets"]

        assert status_data["wallet_strategies"][parent_wallet_name] == parent_strategy_name.value
        assert status_data["wallet_strategies"][clone_wallet_name] == parent_strategy_name.value # Verify inheritance

# To run these tests:
# 1. Ensure pytest and httpx are installed: pip install pytest httpx
# 2. Navigate to the root directory of the project in your terminal.
# 3. Run: pytest
