import pytest
import asyncio
from httpx import AsyncClient

# Adjust the import path according to your project structure
# This assumes your main app instance is named 'app' in 'backend.billion_engine'
from backend.billion_engine import app, wallets, profit_events, wallet_scaling_factors

@pytest.fixture(scope="function", autouse=True)
async def reset_state():
    """Resets the in-memory state before each test."""
    wallets.clear()
    profit_events.clear()
    wallet_scaling_factors.clear()
    # If there are any running asyncio tasks from previous tests that need to be cancelled,
    # that would be more complex and might require managing tasks explicitly.
    # For now, clearing state is the primary concern for these tests.

@pytest.mark.asyncio
async def test_collect_wallet_new():
    """Test collecting a new wallet."""
    async with AsyncClient(app=app, base_url="http://test") as ac:
        response = await ac.post("/collect_wallet", json={"wallet": "test_wallet_1"})
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "registered"
    assert data["wallet"] == "test_wallet_1"
    assert "test_wallet_1" in wallets
    assert "test_wallet_1" in wallet_scaling_factors
    assert wallet_scaling_factors["test_wallet_1"] == 1.0

    # Allow some time for the billion_cycle to start and generate an event
    await asyncio.sleep(0.1) # Reduced sleep for faster tests; may need adjustment

@pytest.mark.asyncio
async def test_collect_wallet_existing():
    """Test collecting an existing wallet."""
    async with AsyncClient(app=app, base_url="http://test") as ac:
        # First call
        await ac.post("/collect_wallet", json={"wallet": "test_wallet_2"})
        # Second call
        response = await ac.post("/collect_wallet", json={"wallet": "test_wallet_2"})

    assert response.status_code == 200 # Should still be successful
    data = response.json()
    assert data["status"] == "registered" # Or a different status like "already_exists" if we change behavior
    assert data["wallet"] == "test_wallet_2"
    # Ensure it wasn't added twice or reset
    assert wallets.count("test_wallet_2") == 1
    assert wallet_scaling_factors.get("test_wallet_2") == 1.0


@pytest.mark.asyncio
async def test_get_profit_events_empty():
    """Test getting profit events for a wallet with no events."""
    async with AsyncClient(app=app, base_url="http://test") as ac:
        response = await ac.get("/profit_events?wallet=non_existent_wallet")
    assert response.status_code == 200
    data = response.json()
    assert data["profitEvents"] == []

@pytest.mark.asyncio
async def test_get_profit_events_with_data():
    """Test getting profit events after a wallet is collected and simulated."""
    wallet_name = "event_wallet_1"
    async with AsyncClient(app=app, base_url="http://test") as ac:
        await ac.post("/collect_wallet", json={"wallet": wallet_name})
        # Wait for billion_cycle to potentially generate some events.
        # This makes the test dependent on timing, which is not ideal but necessary
        # for testing the side effects of the async task in this setup.
        # A very short sleep to allow at least one cycle iteration if possible.
        # The actual profit generation part of billion_cycle has multiple sleeps.
        # We'll check for the wallet's registration and then if any events appear after a longer delay.

        # Give a bit more time for the first profit event to be generated by billion_cycle
        # Original sleeps in billion_cycle: randint(2,5) then 2. So minimum 4 seconds.
        # This is too long for a unit test. We are testing the endpoint, and assuming billion_cycle works.
        # For a true integration test of this, we'd wait longer.
        # Here, we'll manually add a dummy event to test the endpoint's retrieval logic.
        profit_events[wallet_name] = [{"id": "test_evt_1", "amount": 100, "sent": True}]

        response = await ac.get(f"/profit_events?wallet={wallet_name}")

    assert response.status_code == 200
    data = response.json()
    assert len(data["profitEvents"]) == 1
    assert data["profitEvents"][0]["id"] == "test_evt_1"

@pytest.mark.asyncio
async def test_status_empty():
    """Test the status endpoint when no wallets are registered."""
    async with AsyncClient(app=app, base_url="http://test") as ac:
        response = await ac.get("/status")
    assert response.status_code == 200
    data = response.json()
    assert data["wallets"] == []
    assert data["wallet_scaling_factors"] == {}
    assert data["profit_events"] == {}

@pytest.mark.asyncio
async def test_status_with_data():
    """Test the status endpoint after wallets are registered."""
    wallet_name = "status_wallet_1"
    async with AsyncClient(app=app, base_url="http://test") as ac:
        await ac.post("/collect_wallet", json={"wallet": wallet_name})
        # Manually add some data to simulate state for testing the status endpoint directly
        profit_events[wallet_name] = [{"id": "status_evt_1", "amount": 200, "sent": False}]
        # wallet_scaling_factors is set by collect_wallet

        response = await ac.get("/status")

    assert response.status_code == 200
    data = response.json()
    assert wallet_name in data["wallets"]
    assert data["wallet_scaling_factors"][wallet_name] == 1.0
    assert len(data["profit_events"][wallet_name]) == 1
    assert data["profit_events"][wallet_name][0]["id"] == "status_evt_1"

# Note: Testing the full asynchronous behavior of billion_cycle, especially cloning
# and scaling factor changes over time, is complex in unit tests.
# These tests focus on the API contract and immediate state changes.
# More comprehensive testing for billion_cycle would require mocking asyncio.sleep
# or using a dedicated test framework for asynchronous tasks.
# The `asyncio.sleep(0.1)` in `test_collect_wallet_new` is a small concession
# to check if the task starts, but not for its full execution.
# In `test_get_profit_events_with_data` and `test_status_with_data`, we are directly
# manipulating the state variables for more predictable testing of those read-endpoints.
# This is because `billion_cycle` has internal sleeps that are too long for fast unit tests.
# A better approach for `billion_cycle` testing would be to refactor it to make it more testable,
# e.g., by injecting a "time" or "scheduler" object.

# To run these tests:
# 1. Ensure pytest and httpx are installed: pip install pytest httpx
# 2. Navigate to the root directory of the project in your terminal.
# 3. Run: pytest
